### ISSUE TITLE
Consecutive requests not working with $http configuration

### ISSUE THREAD

**Issue by mickelus** [emmaguo/angular-poller#59]
After updating from 0.4.2 to 0.4.3 I'm having some issues with consecutive requests (the first request is still sent) when using a $http configured poller (I have not tried $resource or Restangular). Each consecutive request yields the following error:
```
angular.js:12783 Error: [$http:badreq] Http request configuration url must be a string.  Received: undefined
http://errors.angularjs.org/1.4.10/$http/badreq?p0=undefined
    at http://localhost:3000/bower_components/angular/angular.js:68:12
    at $http (http://localhost:3000/bower_components/angular/angular.js:10498:30)
    at Function.$http.(anonymous function) [as get] (http://localhost:3000/bower_components/angular/angular.js:10743:18)
    at b (http://localhost:3000/bower_components/angular-poller/angular-poller.min.js:2:1334)
    at http://localhost:3000/bower_components/angular/angular.js:15179:52
    at Scope.$eval (http://localhost:3000/bower_components/angular/angular.js:16359:28)
    at Scope.$digest (http://localhost:3000/bower_components/angular/angular.js:16175:31)
    at Scope.$apply (http://localhost:3000/bower_components/angular/angular.js:16467:24)
    at tick (http://localhost:3000/bower_components/angular/angular.js:11598:36)
```

My code: 
```
poller.get('api/ladder', {
    delay: 5000
});
```

**Comment by emmaguo** [comment]
@mickelus : Good catch. It's fixed now in [v0.4.4](https://github.com/emmaguo/angular-poller/releases/tag/v0.4.4). Also added more unit tests. 😃
